# fly.toml app configuration file generated for video-transcription on 2024-02-14T01:01:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'video-transcription'
primary_region = 'ord'
vm.size = 'a100-40gb'

[build]
dockerfile = "Dockerfile"

# TODO: Don't know if we need this since we're not storing data on GPU after script is done;
# look into getting rid of this: https://fly.io/docs/reference/volumes/
[mounts]
source = 'data'
destination = '/data'

[services]
internal_port = 8080
auto_stop_machines = false
auto_start_machines = true
# min_machines_running = 0
# processes = ['app']
