# fly.toml app configuration file generated for lecturesearch-web on 2024-02-20T16:57:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lecturesearch-web'
primary_region = 'ewr'

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"

[http_service]
protocol = "tcp"
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
# min_machines_running = 0
processes = ["app"]

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1
